server {
  listen 80;

  location / {
    proxy_pass http://excalidraw-storage-backend;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}

server {
  listen 8080;

  location /socket.io/ {
    proxy_pass http://excalidraw-room;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

  location / {
    proxy_pass http://excalidraw;
  }
}
